apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      nodeSelector:
        openldap: "true"
      containers:
        - name: jenkins
          image: jenkins/jenkins:2.372
          imagePullPolicy: IfNotPresent
          securityContext:
            # 设置以ROOT用户运行容器
            runAsUser: 0
            privileged: true
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 50000
              name: jenkins-agent
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          hostPath:
            path: /opt/jenkins/home/
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: jenkins
  labels:
    app: jenkins
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30009
    - name: jenkins-agent
      port: 50000
      targetPort: 50000
      nodePort: 30010
  selector:
    app: jenkins